# Generated by Django 6.0.2 on 2026-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
