# Generated by Django 6.0.2 on 2026-06-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_banner_brand_slider_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('top', 'Top Banner'), ('middle', 'Middle Banner'), ('bottom', 'Bottom Banner'), ('side', 'Side Banner')], default='top', max_length=20, verbose_name='Position'),
        ),
    ]
