# Generated by Django 6.0.2 on 2026-07-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
    ]
