# Generated by Django 6.0.2 on 2026-07-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Ignored if this product has variants below', verbose_name='Stock Quantity'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='e.g. S, M, L, XL, 42, 43', max_length=50, verbose_name='Size')),
                ('color', models.CharField(blank=True, help_text='e.g. Black, Red', max_length=50, verbose_name='Color')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the base product price', max_digits=10, null=True, verbose_name='Price Override')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['size', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
