# Generated by Django 6.0.2 on 2026-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_orderitem_variant_label_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_override',
            field=models.PositiveIntegerField(blank=True, help_text='0-100. Leave blank to use the base product discount', null=True, verbose_name='Discount Override (%)'),
        ),
    ]
