# Generated by Django 6.0.2 on 2026-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_coupon_order_discount_amount_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to the whole site. If set, discount only applies to items from these categories.', related_name='coupons', to='products.category', verbose_name='Restrict to Categories'),
        ),
    ]
